### PR TITLE
Street address component

### PR DESCRIPTION
**Pull request by bagby**
Finishes #22 

The Google Places API needs to be enabled for our existing Maps API key in order for this to actually work. (There are acceptance tests that mock the Google Places API so it should Just Work™ once enabled)

### CODE REVIEW

**Comment by bagby** [comment]
@robustdj I added the `aria-label` attribute to the existing dropdown components to make them A11y compliant. Also I took a different approach to the `power-select` positioning using `renderInPlace=true` -- less JS, more CSS ¯\_(ツ)_/¯

**Comment by robustdj** [comment]
@bagby I like your approach of more css, less js more. It would be nice for the `StreetAddress` component to use `Dropdown` since they look and function the same, except that StreetAddress is just a specific implementation of Dropdown. Not sure how much work this would be though. I did a similar refactor in https://github.com/cardstack/ui-components/pull/38 where `PhoneNumber` and `Email` extend the `TextField` component

**Review by robustdj — COMMENTED** [review]
Overall this looks good. The things that are left out are:

* Validations & error message
* Optional flag

These can be filed as a separate ticket, but just noting it so they don't get missed.

As I mentioned before, it would be nice for the StreetAddress component to extend the Dropdown component as well as rolling your css approach to lining up the options into Dropdown. We would just have to make sure that it looks good for single and multi-select.

If it's too large in scope for the current ticket, we should file a separate ticket to come back and DRY this up to make maintaining these components easier in the future.

**Comment by bagby** [comment]
@robustdj I really like your idea about extending the dropdown component, really all this is is a `<Dropdown />` with a custom `search` action. I'd like to merge this and then DRY it up, just to not make the scope too large.

**Comment by bagby** [comment]
As far as validations go, there's not much to worry about with dropdowns, since we are (presumably) supplying valid values, the only thing we really need to worry about is whether or not it's required.

**Pull request merged**
